### ISSUE TITLE
Mid-term Presentation 

### ISSUE THREAD

**Issue by oriol-vall** [Integrated-Project-2-UVic-UCC/covid-device#17]
We wanted to know what you think about our project, what we can improve, some examples, some opinions, all what you say in this issue will be used to upload our Covid Device and our final presentation.

Thanks for your attention!! 

[Mid_term_presentation_Group 1.pdf](https://github.com/Integrated-Project-2-UVic-UCC/covid-device/files/6218180/Mid_term_presentation_Group.1.pdf)

**Comment by marcsala27** [comment]
Hi, as classmates of all of you, we would like to make some comments bout your project and presentation.
First of all, we would like to say that the presentation was pretty good and so clear, starting with the objectives.
You seem to have so clear all of the steps that you are going to follow to make this innovative covid device, but we have a question about the vaporizer. 
How do you know the percentage of hydroalcoholic gel have you to mix with water or are you going to use just water? 
And also another question is about where will the vaporizer with the deposit be situated? Because we understand that it will be able to disinfect the establishment where it will be situated in.
Finally, we want to congratulate you, because some of you showed us some advances and you're able to communicate some electric parts with a mobile phone application and also make the vaporizer work well. 
Thanks!

**Comment by SergiMuac** [comment]
Hi everyone!!

First of all congratulations on your job!!
The presentation was very clear and well prepared and you stick to the time limit very well. But we have a question about humidity control.
As your humidifier is built on your device, and the humidity sensors are inside the establishment, we wonder how are you going to humidify the full establishment if the device is in the entering room. We also wonder which kind of stablishments you thought your device fits in.

In general, it seems that the project is on track. So we encourage you to keep working so hard!

Eye-Sphere Team.

**Comment by XavierPlatas** [comment]
Hi!!
The team of the sun tracking device we want to congratulate you because the presentation was very good and clear! But we have a question about the capacity control.
Will you make it show some kind of warning if the maximum capacity has been reached? It would be very interesting and useful information that customers should know.

Keep working like this!! :)

Sun tracking device Team.

**Comment by omartinezc** [comment]
Good Evening,


Congratulations for the work you are doing, and even more for the focus of the subject to contribute a grain in this great global pandemic. About the last day (mid term presentation), very clear and well organized.

How do you plan to size the device (height)? since the height of the people can vary a lot and it must be accessible.

Thanks.

Very good job in general

Oriol

**Comment by josepmaria-carbonell** [comment]
**Good job guys !** 

Try to answer the questions formulated above, they are very interesting.

@Integrated-Project-2-UVic-UCC/covid-device

**Comment by oriol-vall** [comment]
> Hi, as classmates of all of you, we would like to make some comments bout your project and presentation.
> First of all, we would like to say that the presentation was pretty good and so clear, starting with the objectives.
> You seem to have so clear all of the steps that you are going to follow to make this innovative covid device, but we have a question about the vaporizer.
> How do you know the percentage of hydroalcoholic gel have you to mix with water or are you going to use just water?
> And also another question is about where will the vaporizer with the deposit be situated? Because we understand that it will be able to disinfect the establishment where it will be situated in.
> Finally, we want to congratulate you, because some of you showed us some advances and you're able to communicate some electric parts with a mobile phone application and also make the vaporizer work well.
> Thanks!

Hi, thanks for your attention and your comments!
Our first idea is that we can use only water to make work the vaporizer, but we don't discard the possibility of blending the hydroalcoholic with water when the establishment closed. If we decide to use the second option, we will compute the percentage of the mix. 

The deposit of the vaporizer, will be incorporate in the same humidifier to have better results. 
Thanks for the question!

Covid Device Team.

**Comment by ghost** [comment]
> Good Evening,
> 
> Congratulations for the work you are doing, and even more for the focus of the subject to contribute a grain in this great global pandemic. About the last day (mid term presentation), very clear and well organized.
> 
> How do you plan to size the device (height)? since the height of the people can vary a lot and it must be accessible.
> 
> Thanks.
> 
> Very good job in general
> 
> Oriol


First of all thanks for the support you give us! 
According to the height of the structure, as we take the temperature through the wrist it's not as problematic as if we take the temperature throught the front. 
In our first design, we put the hight of 1.2meter. 
Thanks for the question!

Covid Device Team.

**Comment by oriol-vall** [comment]
> Hi everyone!!
> 
> First of all congratulations on your job!!
> The presentation was very clear and well prepared and you stick to the time limit very well. But we have a question about humidity control.
> As your humidifier is built on your device, and the humidity sensors are inside the establishment, we wonder how are you going to humidify the full establishment if the device is in the entering room. We also wonder which kind of stablishments you thought your device fits in.
> 
> In general, it seems that the project is on track. So we encourage you to keep working so hard!
> 
> Eye-Sphere Team.

First of all thanks for the support you give us!
According to the sensors we can input some sensors connected to the humidifier to have all the time the humidity of the establishment. 
Thanks for the question!

Covid Device Team.

**Comment by ghost** [comment]
> Hi!!
> The team of the sun tracking device we want to congratulate you because the presentation was very good and clear! But we have a question about the capacity control.
> Will you make it show some kind of warning if the maximum capacity has been reached? It would be very interesting and useful information that customers should know.
> 
> Keep working like this!! :)
> 
> Sun tracking device Team.


First of all we want to thank you for the support you give us also congratulate your team for the work you did. 

To answer the question related to the capacity, we are going to monitoring in real time the poeple inside the establishment. Moreover, we are going to implement a buzzer that it will sound when somebody try to enter and the establishment if it's full or if he has fever. 
I hope we have answer the question correctly. 

Thanks!
Covid device team.
